# Development profile - permite actualizar esquema y SQL logging
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Credenciales por defecto para desarrollo
DB_USER=root
DB_PASSWORD=admin
BACKUP_MYSQLDUMP_PATH=C:\Program Files\MySQL\MySQL Server 8.0\bin\mysqldump
